services:

  postgresql:
    container_name: money_transfer_app_pgsql
    image: postgres
    environment:
      POSTGRES_USER: $$$$$
      POSTGRES_PASSWORD: $$$$$
      POSTGRES_DB: transferDB
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5445:5432"
    networks:
      - microservices-money-transfer
    restart: unless-stopped



  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: mt_zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - microservices-money-transfer
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: $$$$$
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    networks:
      - microservices-money-transfer

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: $$$$$
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
    networks:
      - microservices-money-transfer


networks:
  microservices-money-transfer:
    driver: bridge



volumes:
  postgres:

