spring:
  # Database Configuration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5445/account_number_db
    username: moneyTransfer
    password: 12345
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      eclipselink:
        logging:
          level:
            org:
              hibernate:
                SQL: debug
                type:
                  descriptor: trace
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
  # Service Name
  application:
    name: accountNumber-service


account:
  type:
    SAVINGS: "8107"
    CHECKING: "2871"
    BUSINESS: "5790"
    JOINT: "2541"

  branch:
    code:
      MAIN: "6451"
      WEST: "0997"
      EAST: "8012"
      NORTH: "4531"
      SOUTH: "9081"